# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Deploy vss site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
    paths-ignore:
      - "README.md"
      - "archive/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v1
      - name: Install vss cli
        run: make setup
      - name: Build with vss
        run: make build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: ./dist

  # Deployment job
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # ここでダウンロードしないと、デプロイ時に ./dist が無い
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1

